### ISSUE TITLE
Followed all the steps but can't boot in Manjaro

### ISSUE THREAD

**Issue by iTechyTony** [JPyke3/mbp-manjaro#1]
First of all great work, after a successful install and following all the steps. When I select EFI to boot Manjaro, its still boots into macOs

**Comment by JPyke3** [comment]
Thank you for your compliment I appreciate it :)

Unfortunatley the instructions do not match the kernels that are found in the current releases. 

In order to fix this fire up the live usb again. Once you boot into manjaro mount your EFI partition `mount /dev/nvme0n1p1 /mnt` edit the file `nano /mnt/loader/entries/manjaro.conf` and chane the line:
```
linux   /vmlinuz-linux56-mbp
```
to 
```
linux   /vmlinuz-5.6-x86_64-mbp
```
and also change line:
```
initrd  /initramfs-linux56-mbp.img
```
to
```
initrd  /initramfs-5.6-x86_64-mbp.img
```

After that reboot and try that EFI partition again. Let me know how you get on!

**Comment by JPyke3** [comment]
I am recompiling all the images right now to prevent this from happening in the future :)

**Comment by JPyke3** [comment]
Updated the readme in b6e7c4280620ee427da29af8b1e26ad59a2139e9

**Comment by iTechyTony** [comment]
Thank you very much :) it works
