### ISSUE TITLE
[INFO] Wifi 4377 mbp15,4

### ISSUE THREAD

**Issue by GoncaloHit** [JPyke3/mbp-manjaro#11]
Hi and thanks for making this repo, i have followed all the steps, everything seems to be working fine except the WiFi, currently im using my android with USB tethering, i have osx catalina and my wifi firmware seems to be 4377, i have copy pasted  the files correctly from the ftp server provided: 
`'brcmfmac4377-pcie.Apple Inc.-MacbookPro15,4.txt'`
`'brcmfmac4377-pcie.bin'`
`'brcmfmac4377-pcie.clm_blob'`

then i tried the wifi fix from aur and loaded the service and restarted, i then using `iwd` with `iwctl` and used `device list`
and seems to be empty, so i guess my firmware from catalina might not be supported.

also will the new checkm8 exploit on T2 chip make our lifes any easier ? i know i can change laptop but i have a mbp 15,4 from 2019 with touchbar from my company (i have permission to flash linux).
once again thanks for the work,  was easy and simple to install linux with the pre installed kernel

**Comment by JPyke3** [comment]
Hi There!

Sorry that I didn't get back to you, I have been travelling over the past week so haven't had a whole lot of time to do this project.

Anyhow, all good. Would you be able to verify if the WiFi device even appears when running `ip link`. Furthermore, can you see if `brcmfmac` has loaded correctly, either check `lsmod | grep brcmfmac` or check `dmesg` for any output related to `brcmfmac`

Feel free to chuck all the logs in here. I can have a look and maybe give you a hand, as AFIAK your model is supported 👍 

About the Checkm8 exploit: I am in contact with a few people that worked on this, whilst yes, in theory this would help us optimise and get more of the hardware to play a bit nicer with the Linux Kernel, it's still a-lot of work away. In order to do anything really useful we would have to also run Linux on the T2 chip. This wouldn't be possible without a-lot of work on a custom bootloader (Perhaps Coreboot) and a-lot of work to even get the kernel to work on the T2. If you want to follow the progress of that, feel free to join our discord, we post infrequently but at least you could follow along there (It's on the `README` of this repo)

**Comment by JPyke3** [comment]
Closing as it has been a bit since the last reply. If you need this still fixed feel free to comment again!

**Comment by GoncaloHit** [comment]
I will check it out the load of kernel module, but no i dont see any wifi devices.
Thanks
