### ISSUE TITLE
Snap daemon, login service 

### ISSUE THREAD

**Issue by MitchMarq42** [JPyke3/mbp-manjaro#3]
Thank you so much, live usb worked like a charm, plasma on this hidpi screen is glorious, etc. Anyway, after following all instructions in readme.md (as of the time of opening this issue), Manjaro KDE when told to boot (which for some reason requires selecting Windows in the Mac bootloader and Manjaro in the subsequent Windows boot manager-- my attempts to remove the windows startup disk entry have been unsuccessful despite wiping the windows partition, and manjaro will not show up on the main menu) brings up the "Welcome to Manjaro Linux!" line, then shows the standard systemd scrolling, but ends up in a failure loop trying to start either snap daemon, login service, keyboard backlight, or some conbination thereof, extending the expected time for as long as possible and then stopping the service so it can start again. Which leads to it failing to start, and stopping so it can start again, etc... i left it for 3.5 hours and nothing had changed...

Am I doing something wrong? Is this a special proble with the Air? If I delete some files in the manjaro partition will it fix it? Is my screwy bootloader setup the problem? I have not tried any other DE/edition

**Comment by JPyke3** [comment]
Adding some background to this issue from our previous reddit thread, this will ensure that if anyone stumbles upon the same problems they can find a fix:

/u/MitchellMarquez42: 
> I know this probably isn't the right place for an error report, but after following the instructions in Readme.md, and successfully partitioning, installing, and chrooting and on the live USB, I am unable to boot manjaro from the internal nvme-- from the systemd log, it appears that keyboard backlight and screen brightness consistently fail to initialize on MacBook air 2018. Is there a new driver available? I have not seen any updates on the github.

/u/XxPykeexX:
> No worries thanks for letting me know, here is fine but if you really want developers to take notice usually the issues section on GitHub repositories are the way to go. What version of MacOS did you run on the machine before trying to run Linux? And which version of Manjaro did you attempt to run? Maybe to make this easier post this info on a GitHub issue and I will reply there :)

**Comment by JPyke3** [comment]
Thank you for the detailed write up on your issue. Firstly, I imagine your boot loader combination is not the problem (Although it is completely strange and it shouldn't happen) as if you get to Systemd logs upon boot it means you have booted, so im ruling out the boot loader as a problem for now. Also note that it isn't necessarily snapd, or the keyboard, there is a overscanning problem currently on these machines and you cannot see by default the bottom of the Systemd logs.

To me it sounds like some sort of graphics issue. Does the screen completley freeze when you start booting? Is it possible to open up another TTY console on the machine? (You can open another TTY by pressing `ctrl` + `alt` + `F3` using an external keyboard plugged in via USB once you get to the point of failure). The fact that the Live ISO worked indicates that your machine is capable of booting Manjaro, so that is a start, im wondering if either your Intel Integrated graphics driver has failed ([ArchWiki](https://wiki.archlinux.org/index.php/Intel_graphics)) or if your display manager isn't working (In KDE's case it is SDDM [ArchWiki](https://wiki.archlinux.org/index.php/SDDM)).

If there are any extremely obvious logs upon boot that get spammed during the boot sequence over and over again, then let me know what they say either via a photo or by typing them out.

**Comment by JPyke3** [comment]
Hi @MitchMarq42, as I haven't heard from you in a while, I am going to close this issue, if you have any updates feel free to comment again on the issue and I will open it up again :)
